### ISSUE TITLE
Cannot install with Mix

### ISSUE THREAD

**Issue by houshuang** [a13x/aberth#6]
I try to add this with Mix, and I get this error:

```elixir
~/s/ot_text (master) $ mix deps.get
* Updating aberth (git://github.com/a13x/aberth.git)
* Updating lager (git://github.com/basho/lager.git)
* Updating barrel (git://github.com/benoitc/barrel.git)
** (Protocol.UndefinedError) protocol String.Chars not implemented for {:git, 'https://github.com/rcouch/couch_changes.git', {:tag, '1.1.1'}}
    (elixir) lib/string/chars.ex:3: String.Chars.impl_for!/1
    (elixir) lib/string/chars.ex:17: String.Chars.to_string/1
    (mix) lib/mix/rebar.ex:122: Mix.Rebar.compile_req/1
    (mix) lib/mix/rebar.ex:88: Mix.Rebar.parse_dep/2
    (elixir) lib/enum.ex:977: anonymous fn/3 in Enum.map/2
    (elixir) lib/enum.ex:1261: Enum."-reduce/3-lists^foldl/2-0-"/3
    (elixir) lib/enum.ex:977: Enum.map/2
    (mix) lib/mix/dep/loader.ex:250: anonymous fn/2 in Mix.Dep.Loader.rebar_children/1
```

**Comment by a13x** [comment]
Seems like a barrel thing - I just merged a change from benoitc (renaming barrel to barrel_tcp) - mind trying again?
